CREATE TABLE IF NOT EXISTS thumbnail_compositions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  episode_id UUID NOT NULL,
  template_id UUID,
  name VARCHAR(255),
  description TEXT,
  background_frame_asset_id UUID,
  lala_asset_id UUID,
  guest_asset_id UUID,
  justawomen_asset_id UUID,
  justawomaninherprime_asset_id UUID,
  selected_formats JSONB DEFAULT '[]'::jsonb,
  status VARCHAR(50) DEFAULT 'draft',
  created_by VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  current_version INTEGER DEFAULT 1,
  version_history JSONB,
  last_modified_by VARCHAR(100),
  modification_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  is_primary BOOLEAN DEFAULT false,
  composition_config JSONB DEFAULT '{}'::jsonb,
  deleted_at TIMESTAMP
);
