/**
 * Six models are not paranoid (Task #1869).
 *
 * The app's global define (src/config/sequelize.js) sets paranoid: true.
 * The production tables behind these six models have no deleted_at column
 * (docs/audit/EvidenceNote_Canon_Schema_Capture_2026-09-17.txt;
 * docs/SCHEMA_AGREEMENT_READ.md section 2.1), so each model must opt out.
 * Otherwise every read adds `"deleted_at" IS NULL`, every create asks for
 * `RETURNING ... "deleted_at"`, and destroy() issues `UPDATE ... SET
 * "deleted_at"`; all three fail. With paranoid: false, destroy() is a real
 * DELETE, and the last test here pins that.
 *
 * The model files are named once, below. Model and table names are read
 * from the loaded models, not typed again.
 *
 * No database: each real model file is loaded with the app's define on a
 * Sequelize instance that never connects; query() is stubbed to record the
 * generated SQL.
 */
const path = require('path');
const { Sequelize, QueryTypes } = require('sequelize');

const ROOT = path.join(__dirname, '..', '..', '..');
const appConfig = require(path.join(ROOT, 'src', 'config', 'sequelize.js'));

const MODEL_FILES = [
  'CharacterTherapyProfile.js',
  'CharacterArc.js',
  'WardrobeContentAssignment.js',
  'HairLibrary.js',
  'MakeupLibrary.js',
  'UniverseCharacter.js',
];

function loadModel(file) {
  const sequelize = new Sequelize('postgres://unused:unused@localhost:1/unused', {
    dialect: 'postgres',
    logging: false,
    define: appConfig.test.define,
  });
  const captured = [];
  sequelize.query = async (sql, options = {}) => {
    captured.push(typeof sql === 'string' ? sql : sql.query);
    if (options.type === QueryTypes.INSERT) return [options.instance, 1];
    if (options.type === QueryTypes.BULKDELETE) return 0;
    if (options.type === QueryTypes.BULKUPDATE) return 0;
    return [];
  };
  const define = require(path.join(ROOT, 'src', 'models', file));
  const Model = define(sequelize, require('sequelize').DataTypes);
  return { Model, captured };
}

describe('six models: generated SQL has no deleted_at (Task #1869)', () => {
  it('the app define is still paranoid (the premise of this test)', () => {
    expect(appConfig.test.define.paranoid).toBe(true);
  });

  it('names six distinct model files, each defining one model', () => {
    const names = MODEL_FILES.map((f) => loadModel(f).Model.name);
    expect(new Set(names).size).toBe(6);
  });

  describe.each(MODEL_FILES)('%s', (file) => {
    it('options.paranoid === false and no deleted_at attribute', () => {
      const { Model } = loadModel(file);
      expect(Model.options.paranoid).toBe(false);
      expect(Model.rawAttributes.deleted_at).toBeUndefined();
      expect(Model.rawAttributes.deletedAt).toBeUndefined();
    });

    it('findAll SQL has no deleted_at predicate', async () => {
      const { Model, captured } = loadModel(file);
      await Model.findAll({ where: { id: '00000000-0000-0000-0000-000000000000' }, limit: 1 });
      expect(captured).toHaveLength(1);
      expect(captured[0]).toContain(`FROM "${Model.getTableName()}"`);
      expect(captured[0]).not.toMatch(/deleted_at/);
    });

    it('create SQL does not return deleted_at', async () => {
      const { Model, captured } = loadModel(file);
      const values = {};
      for (const [key, attr] of Object.entries(Model.rawAttributes)) {
        if (attr.allowNull === false && attr.defaultValue === undefined && !attr.primaryKey
            && !attr._autoGenerated) {
          values[key] = attr.type.key === 'INTEGER' ? 1
            : attr.type.key === 'UUID' ? '00000000-0000-0000-0000-000000000000'
              : 'x';
        }
      }
      await Model.create(values);
      expect(captured).toHaveLength(1);
      expect(captured[0]).toContain(`INSERT INTO "${Model.getTableName()}"`);
      expect(captured[0]).not.toMatch(/deleted_at/);
    });

    it('destroy() is a real DELETE (the behaviour change Task #1869 makes)', async () => {
      const { Model, captured } = loadModel(file);
      await Model.destroy({ where: { id: '00000000-0000-0000-0000-000000000000' } });
      expect(captured).toHaveLength(1);
      expect(captured[0]).toMatch(new RegExp(`^DELETE FROM "${Model.getTableName()}"`));
      expect(captured[0]).not.toMatch(/deleted_at/);
    });
  });
});
