ALTER TABLE thumbnails ADD COLUMN IF NOT EXISTS position_seconds DECIMAL(8,2);
ALTER TABLE episodes ADD COLUMN IF NOT EXISTS "episodeNumber" INTEGER;
ALTER TABLE episodes ADD COLUMN IF NOT EXISTS "showName" VARCHAR(255);
ALTER TABLE episodes ADD COLUMN IF NOT EXISTS "seasonNumber" INTEGER;
