/**
 * Task #1885 — POST /events/:eventId/proposals/:characterId/approve
 * (src/routes/entanglementRoutes.js) creates its StoryTeller line, and a
 * failure never leaves the proposal approved with no line.
 *
 * StorytellerLine is a schema-checked fake (tests/unit/helpers/schemaCheckedModel.js):
 * a create value naming an undeclared attribute throws, and the create impl
 * below also rejects a missing NOT NULL attribute, as Sequelize's not-null
 * validation does before any SQL. Mocked models, no database.
 *
 * The transaction fake only runs the callback; the atomicity checked here is
 * the ordering inside it (line create before the approval save), so a failed
 * line create never reaches the save.
 */
const express = require('express');
const request = require('supertest');

const MODELS = '../../../src/models';
const AUTH = '../../../src/middleware/auth';

const CHAPTER = '11111111-1111-4111-8111-111111111111';

function passAuth() {
  jest.doMock(AUTH, () => {
    const actual = jest.requireActual(AUTH);
    return { ...actual, requireAuth: (req, _res, next) => { req.user = { id: 'u1' }; next(); } };
  });
}

/** Sequelize rejects a create missing an allowNull:false attribute with no default. */
function assertNotNull(Model, values) {
  for (const [name, attr] of Object.entries(Model.rawAttributes)) {
    // _autoGenerated: createdAt/updatedAt, which Sequelize fills itself.
    if (attr.allowNull === false && !attr.primaryKey && !attr._autoGenerated && attr.defaultValue === undefined
        && (values[name] === undefined || values[name] === null)) {
      throw new Error(`notNull Violation: StorytellerLine.${name} cannot be null`);
    }
  }
}

function setup({ lineCreate } = {}) {
  const { schemaCheckedModel } = require('../helpers/schemaCheckedModel');
  const StorytellerLine = schemaCheckedModel('StorytellerLine', {
    create: lineCreate || (async (values) => ({ id: 'line-1', ...values })),
  });
  // Wrap after the schema check so the NOT NULL rule runs on every create.
  const checkedCreate = StorytellerLine.create.getMockImplementation();
  StorytellerLine.create.mockImplementation(async (values, opts) => {
    assertNotNull(StorytellerLine.Model, values);
    return checkedCreate(values, opts);
  });

  // The stored row: update() replaces it only when called.
  const stored = {
    scene_proposals: [
      { character_id: 'char-1', character_name: 'Amber', brief: 'She sees the post.', approved: false },
      { character_id: 'char-2', character_name: 'Jade', brief: 'Other brief.', approved: false },
    ],
  };
  const event = {
    id: 'ev-1',
    get scene_proposals() { return JSON.parse(JSON.stringify(stored.scene_proposals)); },
    update: jest.fn(async (values) => { Object.assign(stored, JSON.parse(JSON.stringify(values))); return event; }),
  };
  const transaction = jest.fn(async (cb) => cb({ id: 'tx-1' }));

  jest.doMock(MODELS, () => ({
    sequelize: { transaction },
    EntanglementEvent: { findByPk: jest.fn(async () => event) },
    StorytellerLine,
  }));
  jest.doMock('../../../src/services/rippleEngine', () => ({ fireRipple: jest.fn(), resolveEvent: jest.fn() }));
  passAuth();

  const app = express();
  app.use(express.json());
  app.use('/api/v1/entanglements', require('../../../src/routes/entanglementRoutes'));
  return { app, StorytellerLine, event, stored, transaction };
}

const URL = '/api/v1/entanglements/events/ev-1/proposals/char-1/approve';

beforeEach(() => {
  jest.resetModules();
  jest.spyOn(console, 'error').mockImplementation(() => {});
});
afterEach(() => jest.restoreAllMocks());

describe('approve entanglement proposal → StoryTeller line (Task #1885)', () => {
  test('creates the line with declared attributes and saves the approval', async () => {
    const { app, StorytellerLine, event, stored, transaction } = setup();

    const res = await request(app).post(URL).send({ book_id: 'book-1', chapter_id: CHAPTER });

    expect(res.status).toBe(200);
    expect(res.body.proposal).toMatchObject({ character_id: 'char-1', approved: true });
    expect(res.body.message).toBe('Scene proposal approved. Sent to StoryTeller.');

    expect(StorytellerLine.create).toHaveBeenCalledTimes(1);
    const [values, opts] = StorytellerLine.create.mock.calls[0];
    expect(values).toEqual({
      chapter_id: CHAPTER,
      text: '[SCENE BRIEF — from entanglement event · Amber]\n\nShe sees the post.',
      status: 'pending',
      source_tags: ['amber_entanglement'],
    });
    for (const key of Object.keys(values)) expect(StorytellerLine.DECLARED.has(key)).toBe(true);

    // Both writes ran inside the one transaction.
    expect(transaction).toHaveBeenCalledTimes(1);
    expect(opts).toEqual({ transaction: { id: 'tx-1' } });
    expect(event.update).toHaveBeenCalledWith(expect.any(Object), { transaction: { id: 'tx-1' } });

    expect(stored.scene_proposals.find(p => p.character_id === 'char-1').approved).toBe(true);
    expect(stored.scene_proposals.find(p => p.character_id === 'char-2').approved).toBe(false);
  });

  test('a failed line create leaves the proposal unapproved', async () => {
    const { app, StorytellerLine, event, stored } = setup({
      lineCreate: async () => { throw new Error('insert failed'); },
    });

    const res = await request(app).post(URL).send({ book_id: 'book-1', chapter_id: CHAPTER });

    expect(res.status).toBe(500);
    expect(StorytellerLine.create).toHaveBeenCalledTimes(1);
    expect(event.update).not.toHaveBeenCalled();
    // Nothing was saved, so a retry finds the proposal still unapproved.
    expect(stored.scene_proposals.every(p => p.approved === false)).toBe(true);
  });

  test('without book_id + chapter_id it approves and creates no line', async () => {
    const { app, StorytellerLine, stored } = setup();

    const res = await request(app).post(URL).send({});

    expect(res.status).toBe(200);
    expect(res.body.message).toBe('Scene proposal approved.');
    expect(StorytellerLine.create).not.toHaveBeenCalled();
    expect(stored.scene_proposals.find(p => p.character_id === 'char-1').approved).toBe(true);
  });
});
