'use strict';
const { DataTypes } = require('sequelize');

/**
 * Episode Model
 * Represents core episode metadata
 * Uses UUID for id (auto-generated by PostgreSQL)
 */
module.exports = (sequelize) => {
  const Episode = sequelize.define(
    'Episode',
    {
      id: {
        type: DataTypes.UUID,
        primaryKey: true,
        defaultValue: DataTypes.UUIDV4,
        allowNull: false,
      },
      episode_number: {
        type: DataTypes.INTEGER,
        allowNull: true,
      },
      season_number: {
        type: DataTypes.INTEGER,
        allowNull: true,
        field: 'season_number',
      },
      // Season Arc (§8(ff) A5): the slot's season, label ("S1 · E7"), phase
      // and intention, snapshotted at Start Episode or placement.
      season_context: {
        type: DataTypes.JSONB,
        allowNull: true,
      },
      // Episode Money Phase B, MB6 (§8(gg)): the money lines as planned at
      // Start Episode, for the reconciliation after Complete.
      money_plan: {
        type: DataTypes.JSONB,
        allowNull: true,
      },
      title: {
        type: DataTypes.STRING(255),
        allowNull: false,
      },
      // The internal synopsis of what happens (P13, Task #2386). Not viewer
      // copy: the viewer-facing copy is `teaser`.
      description: {
        type: DataTypes.TEXT,
        allowNull: true,
      },
      // Viewer teaser (P12, Task #2386): mystery-driven, never reveals the
      // outcome, hook in the first 150 characters. Auto-drafted at Start
      // Episode; editable through PUT /episodes/:id.
      teaser: {
        type: DataTypes.TEXT,
        allowNull: true,
      },
      // Saved copy of the Start Episode draft. The teaser reads Auto-drafted
      // while it equals this, Edited once it differs (doctrine rule 14).
      teaser_drafted: {
        type: DataTypes.TEXT,
        allowNull: true,
      },
      air_date: {
        type: DataTypes.DATE,
        allowNull: true,
        field: 'air_date',
      },
      status: {
        type: DataTypes.STRING(50),
        allowNull: true,
        defaultValue: 'draft',
      },
      categories: {
        type: DataTypes.JSON,
        allowNull: true,
        defaultValue: [],
        comment: 'Array of category/tag strings for the episode',
      },
      show_id: {
        type: DataTypes.UUID,
        allowNull: true,
        references: {
          model: 'shows',
          key: 'id',
        },
        field: 'show_id',
      },
      created_at: {
        type: DataTypes.DATE,
        allowNull: true,
        defaultValue: DataTypes.NOW,
        field: 'created_at',
      },
      updated_at: {
        type: DataTypes.DATE,
        allowNull: true,
        defaultValue: DataTypes.NOW,
        field: 'updated_at',
      },
      deleted_at: {
        type: DataTypes.DATE,
        allowNull: true,
        field: 'deleted_at',
      },
      thumbnail_url: {
        type: DataTypes.STRING(1024),
        allowNull: true,
        field: 'thumbnail_url',
        comment: 'URL to episode cover image, typically from primary composition',
      },
      current_ai_edit_plan_id: {
        type: DataTypes.UUID,
        allowNull: true,
        field: 'current_ai_edit_plan_id',
        comment: 'Reference to the current AI edit plan for this episode',
      },
      platform: {
        type: DataTypes.STRING(20),
        allowNull: true,
        defaultValue: 'youtube',
        comment: 'Target platform for the episode (youtube, instagram, tiktok, etc.)',
      },
      width: {
        type: DataTypes.INTEGER,
        allowNull: true,
        defaultValue: 1920,
        comment: 'Canvas width in pixels for the target platform',
      },
      height: {
        type: DataTypes.INTEGER,
        allowNull: true,
        defaultValue: 1080,
        comment: 'Canvas height in pixels for the target platform',
      },
      aspect_ratio: {
        type: DataTypes.STRING(10),
        allowNull: true,
        defaultValue: '16:9',
        field: 'aspect_ratio',
        comment: 'Aspect ratio string for the target platform',
      },
      script_content: {
        type: DataTypes.TEXT,
        allowNull: true,
        field: 'script_content',
        comment: 'JSON stringified script data with dialogue blocks',
      },
      evaluation_json: {
        type: DataTypes.JSONB,
        allowNull: true,
        field: 'evaluation_json',
        comment: 'Full evaluation result from scoring engine',
      },
      evaluation_status: {
        type: DataTypes.STRING(20),
        allowNull: true,
        field: 'evaluation_status',
        comment: 'Evaluation workflow status: computed, accepted',
      },
      formula_version: {
        type: DataTypes.STRING(10),
        allowNull: true,
        field: 'formula_version',
        comment: 'Version of the scoring formula used',
      },
      distribution_metadata: {
        type: DataTypes.JSONB,
        allowNull: true,
        field: 'distribution_metadata',
        comment: 'Per-platform distribution: titles, descriptions, hashtags, schedule per platform',
      },
      browse_pool_json: {
        type: DataTypes.JSONB,
        allowNull: true,
        field: 'browse_pool_json',
        comment: 'Generated closet-browse pool for this episode',
      },
      total_income: {
        type: DataTypes.DECIMAL(10, 2),
        allowNull: true,
        defaultValue: 0,
      },
      total_expenses: {
        type: DataTypes.DECIMAL(10, 2),
        allowNull: true,
        defaultValue: 0,
      },
      financial_score: {
        type: DataTypes.INTEGER,
        allowNull: true,
      },
      // Title approval and title card (Task #2386, ruling P11;
      // services/episodeTitleCardService.js). Server-owned: PUT /episodes/:id
      // never writes them.
      title_approved_at: {
        type: DataTypes.DATE,
        allowNull: true,
        comment: 'When the title was approved; the approval holds while title_approved_value equals title',
      },
      title_approved_value: {
        type: DataTypes.TEXT,
        allowNull: true,
        comment: 'The title as approved',
      },
      title_card_asset_id: {
        type: DataTypes.UUID,
        allowNull: true,
        comment: 'The current title card (assets.id)',
      },
      title_card_title: {
        type: DataTypes.TEXT,
        allowNull: true,
        comment: 'The title the current card was designed for; outdated when it differs from title',
      },
      // The title overlay (P11 as amended, 2026-09-30; episodeTitleOverlayService).
      title_overlay_asset_id: {
        type: DataTypes.UUID,
        allowNull: true,
        comment: 'The current title overlay, a transparent PNG (assets.id)',
      },
      title_overlay_title: {
        type: DataTypes.TEXT,
        allowNull: true,
        comment: 'The title the current overlay was made for; outdated when it differs from title',
      },
      title_overlay_style: {
        type: DataTypes.JSONB,
        allowNull: true,
        comment: '{ variant, band: { enabled, opacity }, flourish: { asset_id, url } | null }',
      },
    },
    {
      sequelize,
      modelName: 'Episode',
      tableName: 'episodes',
      timestamps: true,
      underscored: true,
      createdAt: 'created_at',
      updatedAt: 'updated_at',
      paranoid: false, // Manual soft delete via deletedAt
      indexes: [
        {
          name: 'idx_air_date',
          fields: ['air_date'],
        },
        {
          name: 'idx_deleted_at',
          fields: ['deleted_at'],
        },
      ],
      scopes: {
        // Exclude soft-deleted records
        active: {
          where: {
            deleted_at: null,
          },
        },
        // Only deleted records
        deleted: {
          where: {
            deleted_at: {
              [sequelize.Sequelize.Op.ne]: null,
            },
          },
        },
      },
    }
  );

  /**
   * Instance Methods
   */

  /**
   * Set deleted_at and, in the same transaction, sync Lala's coins: under
   * §8(aa) M6 a deleted episode's ledger rows leave her balance, and a
   * restored one's come back (Task #2284).
   */
  async function setDeletedAt(episode, deletedAt) {
    const { syncCoinsAfterEpisodeChange } = require('../services/coinLedgerSync');
    return sequelize.transaction(async (transaction) => {
      episode.deleted_at = deletedAt;
      await episode.save({ transaction });
      await syncCoinsAfterEpisodeChange(sequelize, episode.show_id, { transaction });
      return episode;
    });
  }

  /**
   * Mark episode as deleted (soft delete)
   */
  Episode.prototype.softDelete = async function () {
    return setDeletedAt(this, new Date());
  };

  /**
   * Restore soft-deleted episode
   */
  Episode.prototype.restore = async function () {
    return setDeletedAt(this, null);
  };

  /**
   * Class Methods
   */

  /**
   * Associate Episode with other models
   */
  Episode.associate = function (models) {
    Episode.belongsTo(models.Show, {
      foreignKey: 'show_id',
      as: 'show',
    });

    // Many-to-many with Assets through episode_assets junction table
    Episode.belongsToMany(models.Asset, {
      through: 'episode_assets',
      foreignKey: 'episode_id',
      otherKey: 'asset_id',
      as: 'assets',
    });

    // Many-to-many with Wardrobe through episode_wardrobe junction table
    Episode.belongsToMany(models.Wardrobe, {
      through: 'episode_wardrobe',
      foreignKey: 'episode_id',
      otherKey: 'wardrobe_id',
      as: 'wardrobeItems',
    });

    // Many-to-many with SceneSet through scene_set_episodes
    if (models.SceneSetEpisode) {
      Episode.belongsToMany(models.SceneSet, {
        through: models.SceneSetEpisode,
        foreignKey: 'episode_id',
        otherKey: 'scene_set_id',
        as: 'sceneSets',
      });
    }
  };

  /**
   * Find active episodes (excluding soft-deleted)
   */
  Episode.findActive = function (options = {}) {
    return Episode.scope('active').findAll(options);
  };

  return Episode;
};
