'use strict';
const { DataTypes } = require('sequelize');

/**
 * Episode Model
 * Represents core episode metadata
 * Uses UUID for id (auto-generated by PostgreSQL)
 */
module.exports = (sequelize) => {
  const Episode = sequelize.define(
    'Episode',
    {
      id: {
        type: DataTypes.UUID,
        primaryKey: true,
        defaultValue: DataTypes.UUIDV4,
        allowNull: false,
      },
      episode_number: {
        type: DataTypes.INTEGER,
        allowNull: true,
      },
      title: {
        type: DataTypes.STRING(255),
        allowNull: false,
      },
      description: {
        type: DataTypes.TEXT,
        allowNull: true,
      },
      air_date: {
        type: DataTypes.DATE,
        allowNull: true,
        field: 'air_date',
      },
      status: {
        type: DataTypes.STRING(50),
        allowNull: true,
        defaultValue: 'draft',
      },
      categories: {
        type: DataTypes.JSON,
        allowNull: true,
        defaultValue: [],
        comment: 'Array of category/tag strings for the episode',
      },
      show_id: {
        type: DataTypes.UUID,
        allowNull: true,
        references: {
          model: 'shows',
          key: 'id',
        },
        field: 'show_id',
      },
      created_at: {
        type: DataTypes.DATE,
        allowNull: true,
        defaultValue: DataTypes.NOW,
        field: 'created_at',
      },
      updated_at: {
        type: DataTypes.DATE,
        allowNull: true,
        defaultValue: DataTypes.NOW,
        field: 'updated_at',
      },
      deleted_at: {
        type: DataTypes.DATE,
        allowNull: true,
        field: 'deleted_at',
      },
    },
    {
      sequelize,
      modelName: 'Episode',
      tableName: 'episodes',
      timestamps: true,
      underscored: true,
      createdAt: 'created_at',
      updatedAt: 'updated_at',
      paranoid: false, // Manual soft delete via deletedAt
      indexes: [
        {
          name: 'idx_air_date',
          fields: ['air_date'],
        },
        {
          name: 'idx_deleted_at',
          fields: ['deleted_at'],
        },
      ],
      scopes: {
        // Exclude soft-deleted records
        active: {
          where: {
            deleted_at: null,
          },
        },
        // Only deleted records
        deleted: {
          where: {
            deleted_at: {
              [sequelize.Sequelize.Op.ne]: null,
            },
          },
        },
      },
    }
  );

  /**
   * Instance Methods
   */

  /**
   * Mark episode as deleted (soft delete)
   */
  Episode.prototype.softDelete = async function () {
    this.deleted_at = new Date();
    return this.save();
  };

  /**
   * Restore soft-deleted episode
   */
  Episode.prototype.restore = async function () {
    this.deleted_at = null;
    return this.save();
  };

  /**
   * Class Methods
   */

  /**
   * Associate Episode with other models
   */
  Episode.associate = function (models) {
    Episode.belongsTo(models.Show, {
      foreignKey: 'show_id',
      as: 'show',
    });
  };

  /**
   * Find active episodes (excluding soft-deleted)
   */
  Episode.findActive = function (options = {}) {
    return Episode.scope('active').findAll(options);
  };

  return Episode;
};
