'use strict';
const { DataTypes } = require('sequelize');

/**
 * Episode Model
 * Represents core episode metadata
 * Uses UUID for id (auto-generated by PostgreSQL)
 */
module.exports = (sequelize) => {
  const Episode = sequelize.define('Episode', {
    id: {
      type: DataTypes.UUID,
      primaryKey: true,
      defaultValue: DataTypes.UUIDV4,
      allowNull: false,
    },
    episode_number: {
      type: DataTypes.INTEGER,
      allowNull: true,
    },
    title: {
      type: DataTypes.STRING(255),
      allowNull: false,
    },
    description: {
      type: DataTypes.TEXT,
      allowNull: true,
    },
    air_date: {
      type: DataTypes.DATE,
      allowNull: true,
      field: 'air_date',
    },
    status: {
      type: DataTypes.STRING(50),
      allowNull: true,
      defaultValue: 'draft',
    },
    categories: {
      type: DataTypes.JSON,
      allowNull: true,
      defaultValue: [],
      comment: 'Array of category/tag strings for the episode',
    },
    created_at: {
      type: DataTypes.DATE,
      allowNull: true,
      defaultValue: DataTypes.NOW,
      field: 'created_at',
    },
    updated_at: {
      type: DataTypes.DATE,
      allowNull: true,
      defaultValue: DataTypes.NOW,
      field: 'updated_at',
    },
    deleted_at: {
      type: DataTypes.DATE,
      allowNull: true,
      field: 'deleted_at',
    },

    // DEPRECATED FIELDS - kept for backward compatibility
    showName: {
      type: DataTypes.STRING(255),
      allowNull: true,
      field: 'showName', // Explicitly map to database column
    },
    seasonNumber: {
      type: DataTypes.INTEGER,
      allowNull: true,
      field: 'seasonNumber', // Explicitly map to database column
    },
    episodeNumber: {
      type: DataTypes.INTEGER,
      allowNull: true,
      field: 'episodeNumber', // Explicitly map to database column
    },
    episodeTitle: {
      type: DataTypes.STRING(255),
      allowNull: true,
      field: 'episodeTitle', // Explicitly map to database column
    },
    plotSummary: {
      type: DataTypes.TEXT,
      allowNull: true,
      field: 'plotSummary', // Explicitly map to database column
    },
    director: {
      type: DataTypes.STRING(255),
      allowNull: true,
      field: 'director', // Explicitly map to database column
    },
    writer: {
      type: DataTypes.STRING(255),
      allowNull: true,
      field: 'writer', // Explicitly map to database column
    },
    durationMinutes: {
      type: DataTypes.INTEGER,
      allowNull: true,
      field: 'durationMinutes', // Explicitly map to database column
    },
    rating: {
      type: DataTypes.DECIMAL(3, 1),
      allowNull: true,
      field: 'rating', // Explicitly map to database column
    },
    genre: {
      type: DataTypes.STRING(100),
      allowNull: true,
      field: 'genre', // Explicitly map to database column
    },

    // Media references
    thumbnailUrl: {
      type: DataTypes.STRING(512),
      allowNull: true,
      field: 'thumbnailUrl', // Explicitly map to database column
    },
    posterUrl: {
      type: DataTypes.STRING(512),
      allowNull: true,
      field: 'posterUrl', // Explicitly map to database column
    },
    videoUrl: {
      type: DataTypes.STRING(512),
      allowNull: true,
      validate: {
        isUrl: true,
      },
      field: 'videoUrl', // Explicitly map to database column
    },

    // S3 references
    rawVideoS3Key: {
      type: DataTypes.STRING(512),
      allowNull: true,
      comment: 'S3 key for original uploaded video',
      field: 'rawVideoS3Key', // Explicitly map to database column
    },
    processedVideoS3Key: {
      type: DataTypes.STRING(512),
      allowNull: true,
      comment: 'S3 key for processed/encoded video',
      field: 'processedVideoS3Key', // Explicitly map to database column
    },
    metadataJsonS3Key: {
      type: DataTypes.STRING(512),
      allowNull: true,
      comment: 'S3 key for extracted metadata JSON',
      field: 'metadataJsonS3Key', // Explicitly map to database column
    },

    // Status tracking
    processingStatus: {
      type: DataTypes.ENUM('pending', 'processing', 'complete', 'failed'),
      defaultValue: 'pending',
      comment: 'Current processing status of episode',
      field: 'processingStatus', // Explicitly map to database column
    },
  }, {
    sequelize,
    modelName: 'Episode',
    tableName: 'episodes',
    timestamps: true,
    underscored: true,
    createdAt: 'created_at',
    updatedAt: 'updated_at',
    paranoid: false, // Manual soft delete via deletedAt
    indexes: [
      {
        name: 'idx_show_season_episode',
        fields: ['showName', 'seasonNumber', 'episodeNumber'],
        unique: true,
      },
      {
        name: 'idx_air_date',
        fields: ['air_date'],
      },
      {
        name: 'idx_processing_status',
        fields: ['processingStatus'],
      },
      {
        name: 'idx_deleted_at',
        fields: ['deleted_at'],
      },
    ],
    scopes: {
      // Exclude soft-deleted records
      active: {
        where: {
          deletedAt: null,
        },
      },
      // Only deleted records
      deleted: {
        where: {
          deletedAt: {
            [sequelize.Sequelize.Op.ne]: null,
          },
        },
      },
      // Processing episodes
      processing: {
        where: {
          processingStatus: 'processing',
        },
      },
      // Failed episodes
      failed: {
        where: {
          processingStatus: 'failed',
        },
      },
    },
  });

  /**
   * Instance Methods
   */

  /**
   * Mark episode as deleted (soft delete)
   */
  Episode.prototype.softDelete = async function() {
    this.deletedAt = new Date();
    return this.save();
  };

  /**
   * Restore soft-deleted episode
   */
  Episode.prototype.restore = async function() {
    this.deletedAt = null;
    return this.save();
  };

  /**
   * Update processing status
   */
  Episode.prototype.updateStatus = async function(status) {
    if (!['pending', 'processing', 'complete', 'failed'].includes(status)) {
      throw new Error('Invalid processing status');
    }
    this.processingStatus = status;
    return this.save();
  };

  /**
   * Get S3 bucket and key information
   */
  Episode.prototype.getS3Info = function() {
    return {
      bucket: process.env.AWS_S3_BUCKET_STORAGE || 'episode-metadata-storage-dev',
      keys: {
        raw: this.rawVideoS3Key,
        processed: this.processedVideoS3Key,
        metadata: this.metadataJsonS3Key,
      },
    };
  };

  /**
   * Class Methods
   */

  /**
   * Find active episodes (excluding soft-deleted)
   */
  Episode.findActive = function(options = {}) {
    return Episode.scope('active').findAll(options);
  };

  /**
   * Find by show name and season
   */
  Episode.findBySeason = async function(showName, seasonNumber) {
    return Episode.scope('active').findAll({
      where: { showName, seasonNumber },
      order: [['episodeNumber', 'ASC']],
    });
  };

  /**
   * Find by show name, season, and episode number
   */
  Episode.findByEpisodeNumber = async function(showName, seasonNumber, episodeNumber) {
    return Episode.scope('active').findOne({
      where: { showName, seasonNumber, episodeNumber },
    });
  };

  /**
   * Get processing queue information
   */
  Episode.getProcessingStatus = async function(id) {
    const episode = await Episode.findByPk(id, {
      attributes: ['id', 'episodeTitle', 'processingStatus', 'uploadDate'],
    });
    return episode;
  };

  /**
   * Get episodes requiring processing
   */
  Episode.getPendingProcessing = function() {
    return Episode.scope(['active', 'processing']).findAll({
      order: [['uploadDate', 'ASC']],
    });
  };

  return Episode;
};
